import { NextRequest, NextResponse } from "next/server";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ENV_PATH = resolve(process.cwd(), "..", "..", ".env.local");

function readEnvFile(): Record<string, string> {
  if (!existsSync(ENV_PATH)) return {};
  const raw = readFileSync(ENV_PATH, "utf-8");
  const vars: Record<string, string> = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (key) vars[key] = val;
  }
  return vars;
}

function writeEnvFile(vars: Record<string, string>): void {
  const lines: string[] = [];
  lines.push("# SahamLens environment — generated by Config UI");
  lines.push("# WARNING: local changes may be overwritten by Config UI");
  lines.push("");
  const keys = Object.keys(vars).sort();
  for (const key of keys) {
    lines.push(`${key}=${vars[key] ?? ""}`);
  }
  writeFileSync(ENV_PATH, lines.join("\n") + "\n", "utf-8");
}

export async function GET(req: NextRequest): Promise<NextResponse> {
  const section = req.nextUrl.searchParams.get("section");

  if (!section || !["llm", "app"].includes(section)) {
    return NextResponse.json({ error: "Unknown section. Use ?section=llm|app" }, { status: 400 });
  }

  const env = readEnvFile();

  if (section === "llm") {
    return NextResponse.json({
      section: "llm",
      config: {
        provider: env.SAHAMLENS_LLM_PROVIDER ?? "",
        baseUrl: env.SAHAMLENS_LLM_BASE_URL ?? "",
        model: env.SAHAMLENS_LLM_MODEL ?? "",
      },
    });
  }

  return NextResponse.json({
    section: "app",
    config: {
      dataDir: env.DUCKDB_PATH ?? "./data/private/sahamlens.duckdb",
    },
  });
}

export async function POST(req: NextRequest): Promise<NextResponse> {
  const section = req.nextUrl.searchParams.get("section");

  if (!section || !["llm", "app"].includes(section)) {
    return NextResponse.json({ error: "Unknown section. Use ?section=llm|app" }, { status: 400 });
  }

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const env = readEnvFile();

  if (section === "app") {
    return NextResponse.json({ error: "App section is read-only" }, { status: 400 });
  }

  if (section === "llm") {
    if (typeof body.provider === "string") env.SAHAMLENS_LLM_PROVIDER = body.provider;
    if (typeof body.baseUrl === "string") env.SAHAMLENS_LLM_BASE_URL = body.baseUrl;
    if (typeof body.model === "string") env.SAHAMLENS_LLM_MODEL = body.model;
    if (typeof body.apiKey === "string") env.SAHAMLENS_LLM_API_KEY = body.apiKey; // pragma: allowlist secret
  }

  writeEnvFile(env);
  return NextResponse.json({ ok: true, section });
}
