"""Local alert lifecycle package."""

from packages.core.alerts.evaluator import evaluate_active_alert_rules, evaluate_alert_rule
from packages.core.alerts.models import (
    AlertDeliveryAttempt,
    AlertEvaluation,
    AlertEvaluationInput,
    AlertEvaluationResult,
    AlertEvent,
    AlertRule,
    AlertRuleInput,
)
from packages.core.alerts.repo import (
    acknowledge_alert_event,
    archive_alert_rule,
    create_alert_rule,
    dismiss_alert_event,
    get_alert_event,
    get_alert_rule,
    insert_alert_evaluation,
    insert_alert_event,
    list_alert_delivery_attempts,
    list_alert_events,
    list_alert_rules,
    mark_alert_event_false_positive,
    pause_alert_rule,
    resolve_alert_event,
)
from packages.core.alerts.telegram import (
    TelegramConfigStatus,
    TelegramDeliveryResult,
    TelegramSendResponse,
    format_telegram_alert_message,
    get_telegram_status,
    send_alert_event_to_telegram,
)

__all__ = [
    "AlertDeliveryAttempt",
    "AlertEvaluation",
    "AlertEvaluationInput",
    "AlertEvaluationResult",
    "AlertEvent",
    "AlertRule",
    "AlertRuleInput",
    "TelegramConfigStatus",
    "TelegramDeliveryResult",
    "TelegramSendResponse",
    "acknowledge_alert_event",
    "archive_alert_rule",
    "create_alert_rule",
    "dismiss_alert_event",
    "evaluate_active_alert_rules",
    "evaluate_alert_rule",
    "format_telegram_alert_message",
    "get_alert_event",
    "get_alert_rule",
    "get_telegram_status",
    "insert_alert_evaluation",
    "insert_alert_event",
    "list_alert_delivery_attempts",
    "list_alert_events",
    "list_alert_rules",
    "mark_alert_event_false_positive",
    "pause_alert_rule",
    "resolve_alert_event",
    "send_alert_event_to_telegram",
]
